version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${REGISTRY_LOGIN_SERVER}/api-sakila:${TAG}"
    container_name: ctSakila
    ports:
      - "8081:8080" 
      - "3443:443"
    networks:
      - lasalle  
networks:
    lasalle:
        driver: bridge  